builds:
- id: yana1205-test-sample-app
  main: ./cmd
  binary: bin/yana1205-test-sample-app
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
brews:
  - name: yana1205-test-sample-app
    homepage: "https://github.com/yana1205-test/sample-app"
    description: "sample app for my study"
    repository:
      owner: yana1205-test
      name: sample-app
      branch: main
      pull_request:
        enabled: false
