# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yana1205TestSampleApp < Formula
  desc "sample app for my study"
  homepage "https://github.com/yana1205-test/sample-app/go"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.1.0/sample-app_0.1.0_darwin_arm64.tar.gz"
      sha256 "2cc6d0db9eada0402f1d794c478877e787102a677a96952b77bf96c4c031926b"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.1.0/sample-app_0.1.0_darwin_amd64.tar.gz"
      sha256 "7ac7855483bb9f3ea5c260619552e22c669330a57a4fab0c07b0ada3f7b94e9f"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.1.0/sample-app_0.1.0_linux_arm64.tar.gz"
      sha256 "27cba77040f309e2690e4176b85c1f6ee627d067b67990f5025982f3952d965f"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.1.0/sample-app_0.1.0_linux_amd64.tar.gz"
      sha256 "017148271024e5e77ec7e04de0882e7ad9d4cd968049be4ec13358e7f2a2d28b"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
  end
end
