# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yana1205TestSampleApp < Formula
  desc "sample app for my study"
  homepage "https://github.com/yana1205-test/sample-app/go"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.4.0/sample-app_0.4.0_darwin_arm64.tar.gz"
      sha256 "a7c838c480eb22eef8eec6e6c8624594b17ef3105c085f6f84cd43fbf4fd736e"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.4.0/sample-app_0.4.0_darwin_amd64.tar.gz"
      sha256 "5724267d0490fe2b74904aa0428f0577a3d98b66c4010f8b541432f9215371a6"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.4.0/sample-app_0.4.0_linux_arm64.tar.gz"
      sha256 "62bd70e5d6b8e9ef4a4d66d43e42e421775808875624653a084de6419b2c993f"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yana1205-test/sample-app/releases/download/v0.4.0/sample-app_0.4.0_linux_amd64.tar.gz"
      sha256 "1598d8d0c057692c6b3ed5ccce6edf2ca8cc907c1cbe753f2f4e3e67d4ae1684"

      def install
        bin.install "bin/yana1205-test-sample-app"
      end
    end
  end
end
