name: Release

on:
  push:
    tags:
      - 'go/v*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3

    - name: Release
      run: |
        cd go
        make release GOARCH=arm64
        make release GOARCH=amd64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}